[package]
name = "ampullator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.9.1"
tempfile = "3.11.0"

[profile.release]
debug = false

